#!/usr/bin/env python3
"""Generate 1-degree resolution sin/cos/tan lookup tables for trig_lut.h"""

import math
import sys

N = 360

def gen():
    out = []
    out.append("// Auto-generated by generate_lut.py -- 1-degree resolution trig LUT")
    out.append("// Do not edit by hand.")
    out.append("")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define TRIG_LUT_SIZE {N}")
    out.append("")

    # sin
    out.append(f"static const float sin_lut[{N}] = {{")
    for i in range(N):
        v = math.sin(math.radians(i))
        out.append(f"  {v:11.7f}f,")
    out.append("};")
    out.append("")

    # cos
    out.append(f"static const float cos_lut[{N}] = {{")
    for i in range(N):
        v = math.cos(math.radians(i))
        out.append(f"  {v:11.7f}f,")
    out.append("};")
    out.append("")

    # tan
    out.append(f"static const float tan_lut[{N}] = {{")
    for i in range(N):
        if (i - 90) % 180 == 0:
            v = float('nan')
        else:
            v = math.tan(math.radians(i))
        out.append(f"  {v:11.7f}f,")
    out.append("};")
    out.append("")

    # fast sin/cos by degree index (inline helpers)
    out.append("// Index with degrees [0..359]; negative wraps automatically")
    out.append("static inline float sin_deg(int d) {")
    out.append("  d = (d % 360 + 360) % 360;")
    out.append("  return sin_lut[d];")
    out.append("}")
    out.append("")
    out.append("static inline float cos_deg(int d) {")
    out.append("  d = (d % 360 + 360) % 360;")
    out.append("  return cos_lut[d];")
    out.append("}")
    out.append("")

    sys.stdout.write("\n".join(out))

if __name__ == "__main__":
    gen()
